teasdfst: add files

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,10 +1,44 @@
-#!/usr/bin/env bash
-echo $1
-if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
-    exit 1
-fi
-if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
-    echo "Aborting commit. Your commit message is too long." >&2
-    exit 1
+#!/usr/bin/env sh
+
+# Pre-receive hook that will block commits with messges that do not follow regex rule
+
+commit_msg_type_regex='feat|fix|refactor|style|test|docs|build'
+commit_msg_scope_regex='.{1,20}'
+commit_msg_subject_regex='.{1,100}'
+commit_msg_regex="^(${commit_msg_type_regex})(\(${commit_msg_scope_regex}\))?: (${commit_msg_subject_regex})\$"
+merge_msg_regex="^Merge branch '.+'\$"
+revert_msg_regex="^Revert \".+\"\$"
+
+zero_commit="0000000000000000000000000000000000000000"
+
+# Do not traverse over commits that are already in the repository
+excludeExisting="--not --all"
+
+error=""
+while read oldrev newrev refname; do
+  # branch or tag get deleted
+  if [ "$newrev" = "$zero_commit" ]; then
+    continue
+  fi
+
+  # Check for new branch or tag
+  if [ "$oldrev" = "$zero_commit" ]; then
+    rev_span=`git rev-list $newrev $excludeExisting`
+  else
+    rev_span=`git rev-list $oldrev..$newrev $excludeExisting`
+  fi
+
+  for commit in $rev_span; do
+    commit_msg_header=$(git show -s --format=%s $commit)
+    if ! [[ "$commit_msg_header" =~ (${commit_msg_regex})|(${merge_msg_regex})|(${revert_msg_regex}) ]]; then
+      echo "$commit" >&2
+      echo "ERROR: Invalid commit message format" >&2
+      echo "$commit_msg_header" >&2
+      error="true"
+    fi
+  done
+done
+
+if [ -n "$error" ]; then
+  exit 1
 fi
